server:
  port: 9001

spring:
  application:
    name: cloud-user-login
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
        register: true

